---
dist: trusty
services:
  - docker
language: go
go:
  - 1.13.x

install:
  # - bash scripts/gogetcookie.sh
  - make build

script:
  - make test
  - make vet
  - make website-test

branches:
  only:
    - master
matrix:
  fast_finish: true
  allow_failures:
    - go: tip