dist: xenial
os: linux
services:
  - docker
language: go

env:
  global: GOFLAGS=-mod=vendor

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - go: "1.13.x"
      name: "Code Lint"
      script: make lint
    - go: "1.13.x"
      name: "Code UnitTest"
      script: make test
    - go: "1.13.x"
      name: "Dependencies"
      script: make depscheck

install:
  - make tools

branches:
  only:
    - master