---
dist: trusty
os: linux
services:
  - docker
language: go
go:
  - 1.13.x

install:
  # - bash scripts/gogetcookie.sh
  - make build

script:
  - make test
  - make vet

branches:
  only:
    - master
jobs:
  fast_finish: true
  allow_failures:
    - go: tip